name: drums_act
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/BGDRUMS.jpg
    - assets/images/KICK.png
    - assets/images/SNARE.png
    - assets/images/TOM.png
    - assets/images/CRASH.png
    - assets/images/SPLASH.png
    - assets/images/RIDE.png
    - assets/images/FLOOR.png
    - assets/images/OPEN.png
    - assets/images/CLOSEHH.png
    - assets/kick.mp3
    - assets/closehh.mp3
    - assets/crashl.mp3
    - assets/crashr.mp3
    - assets/crashm.mp3
    - assets/floor.mp3
    - assets/openhh.mp3
    - assets/ride.mp3
    - assets/tom1.mp3
    - assets/tom2.mp3
    - assets/tom3.mp3
    - assets/snare.mp3
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
